/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123LocaleChar125RouteImport } from './routes/{-$locale}'
import { Route as Char123LocaleChar125IndexRouteImport } from './routes/{-$locale}.index'
import { Route as Char123LocaleChar125TemplatesRouteImport } from './routes/{-$locale}.templates'
import { Route as Char123LocaleChar125CvsRouteImport } from './routes/{-$locale}.cvs'
import { Route as Char123LocaleChar125CvPrintRouteImport } from './routes/{-$locale}.cv.print'
import { Route as Char123LocaleChar125CvEditRouteImport } from './routes/{-$locale}.cv.edit'

const Char123LocaleChar125Route = Char123LocaleChar125RouteImport.update({
  id: '/{-$locale}',
  path: '/{-$locale}',
  getParentRoute: () => rootRouteImport,
} as any)
const Char123LocaleChar125IndexRoute =
  Char123LocaleChar125IndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125TemplatesRoute =
  Char123LocaleChar125TemplatesRouteImport.update({
    id: '/templates',
    path: '/templates',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CvsRoute = Char123LocaleChar125CvsRouteImport.update({
  id: '/cvs',
  path: '/cvs',
  getParentRoute: () => Char123LocaleChar125Route,
} as any)
const Char123LocaleChar125CvPrintRoute =
  Char123LocaleChar125CvPrintRouteImport.update({
    id: '/cv/print',
    path: '/cv/print',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)
const Char123LocaleChar125CvEditRoute =
  Char123LocaleChar125CvEditRouteImport.update({
    id: '/cv/edit',
    path: '/cv/edit',
    getParentRoute: () => Char123LocaleChar125Route,
  } as any)

export interface FileRoutesByFullPath {
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/cvs': typeof Char123LocaleChar125CvsRoute
  '/{-$locale}/templates': typeof Char123LocaleChar125TemplatesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/cv/edit': typeof Char123LocaleChar125CvEditRoute
  '/{-$locale}/cv/print': typeof Char123LocaleChar125CvPrintRoute
}
export interface FileRoutesByTo {
  '/{-$locale}/cvs': typeof Char123LocaleChar125CvsRoute
  '/{-$locale}/templates': typeof Char123LocaleChar125TemplatesRoute
  '/{-$locale}': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/cv/edit': typeof Char123LocaleChar125CvEditRoute
  '/{-$locale}/cv/print': typeof Char123LocaleChar125CvPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/{-$locale}': typeof Char123LocaleChar125RouteWithChildren
  '/{-$locale}/cvs': typeof Char123LocaleChar125CvsRoute
  '/{-$locale}/templates': typeof Char123LocaleChar125TemplatesRoute
  '/{-$locale}/': typeof Char123LocaleChar125IndexRoute
  '/{-$locale}/cv/edit': typeof Char123LocaleChar125CvEditRoute
  '/{-$locale}/cv/print': typeof Char123LocaleChar125CvPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/{-$locale}'
    | '/{-$locale}/cvs'
    | '/{-$locale}/templates'
    | '/{-$locale}/'
    | '/{-$locale}/cv/edit'
    | '/{-$locale}/cv/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/{-$locale}/cvs'
    | '/{-$locale}/templates'
    | '/{-$locale}'
    | '/{-$locale}/cv/edit'
    | '/{-$locale}/cv/print'
  id:
    | '__root__'
    | '/{-$locale}'
    | '/{-$locale}/cvs'
    | '/{-$locale}/templates'
    | '/{-$locale}/'
    | '/{-$locale}/cv/edit'
    | '/{-$locale}/cv/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  Char123LocaleChar125Route: typeof Char123LocaleChar125RouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$locale}': {
      id: '/{-$locale}'
      path: '/{-$locale}'
      fullPath: '/{-$locale}'
      preLoaderRoute: typeof Char123LocaleChar125RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/{-$locale}/': {
      id: '/{-$locale}/'
      path: '/'
      fullPath: '/{-$locale}/'
      preLoaderRoute: typeof Char123LocaleChar125IndexRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/templates': {
      id: '/{-$locale}/templates'
      path: '/templates'
      fullPath: '/{-$locale}/templates'
      preLoaderRoute: typeof Char123LocaleChar125TemplatesRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/cvs': {
      id: '/{-$locale}/cvs'
      path: '/cvs'
      fullPath: '/{-$locale}/cvs'
      preLoaderRoute: typeof Char123LocaleChar125CvsRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/cv/print': {
      id: '/{-$locale}/cv/print'
      path: '/cv/print'
      fullPath: '/{-$locale}/cv/print'
      preLoaderRoute: typeof Char123LocaleChar125CvPrintRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
    '/{-$locale}/cv/edit': {
      id: '/{-$locale}/cv/edit'
      path: '/cv/edit'
      fullPath: '/{-$locale}/cv/edit'
      preLoaderRoute: typeof Char123LocaleChar125CvEditRouteImport
      parentRoute: typeof Char123LocaleChar125Route
    }
  }
}

interface Char123LocaleChar125RouteChildren {
  Char123LocaleChar125CvsRoute: typeof Char123LocaleChar125CvsRoute
  Char123LocaleChar125TemplatesRoute: typeof Char123LocaleChar125TemplatesRoute
  Char123LocaleChar125IndexRoute: typeof Char123LocaleChar125IndexRoute
  Char123LocaleChar125CvEditRoute: typeof Char123LocaleChar125CvEditRoute
  Char123LocaleChar125CvPrintRoute: typeof Char123LocaleChar125CvPrintRoute
}

const Char123LocaleChar125RouteChildren: Char123LocaleChar125RouteChildren = {
  Char123LocaleChar125CvsRoute: Char123LocaleChar125CvsRoute,
  Char123LocaleChar125TemplatesRoute: Char123LocaleChar125TemplatesRoute,
  Char123LocaleChar125IndexRoute: Char123LocaleChar125IndexRoute,
  Char123LocaleChar125CvEditRoute: Char123LocaleChar125CvEditRoute,
  Char123LocaleChar125CvPrintRoute: Char123LocaleChar125CvPrintRoute,
}

const Char123LocaleChar125RouteWithChildren =
  Char123LocaleChar125Route._addFileChildren(Char123LocaleChar125RouteChildren)

const rootRouteChildren: RootRouteChildren = {
  Char123LocaleChar125Route: Char123LocaleChar125RouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
