/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TemplatesRouteImport } from './routes/templates'
import { Route as ProfilesRouteImport } from './routes/profiles'
import { Route as CvsRouteImport } from './routes/cvs'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CvPrintRouteImport } from './routes/cv.print'
import { Route as CvEditRouteImport } from './routes/cv.edit'

const TemplatesRoute = TemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilesRoute = ProfilesRouteImport.update({
  id: '/profiles',
  path: '/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const CvsRoute = CvsRouteImport.update({
  id: '/cvs',
  path: '/cvs',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CvPrintRoute = CvPrintRouteImport.update({
  id: '/cv/print',
  path: '/cv/print',
  getParentRoute: () => rootRouteImport,
} as any)
const CvEditRoute = CvEditRouteImport.update({
  id: '/cv/edit',
  path: '/cv/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cvs': typeof CvsRoute
  '/profiles': typeof ProfilesRoute
  '/templates': typeof TemplatesRoute
  '/cv/edit': typeof CvEditRoute
  '/cv/print': typeof CvPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cvs': typeof CvsRoute
  '/profiles': typeof ProfilesRoute
  '/templates': typeof TemplatesRoute
  '/cv/edit': typeof CvEditRoute
  '/cv/print': typeof CvPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cvs': typeof CvsRoute
  '/profiles': typeof ProfilesRoute
  '/templates': typeof TemplatesRoute
  '/cv/edit': typeof CvEditRoute
  '/cv/print': typeof CvPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cvs'
    | '/profiles'
    | '/templates'
    | '/cv/edit'
    | '/cv/print'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cvs' | '/profiles' | '/templates' | '/cv/edit' | '/cv/print'
  id:
    | '__root__'
    | '/'
    | '/cvs'
    | '/profiles'
    | '/templates'
    | '/cv/edit'
    | '/cv/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CvsRoute: typeof CvsRoute
  ProfilesRoute: typeof ProfilesRoute
  TemplatesRoute: typeof TemplatesRoute
  CvEditRoute: typeof CvEditRoute
  CvPrintRoute: typeof CvPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/templates': {
      id: '/templates'
      path: '/templates'
      fullPath: '/templates'
      preLoaderRoute: typeof TemplatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profiles': {
      id: '/profiles'
      path: '/profiles'
      fullPath: '/profiles'
      preLoaderRoute: typeof ProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cvs': {
      id: '/cvs'
      path: '/cvs'
      fullPath: '/cvs'
      preLoaderRoute: typeof CvsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/print': {
      id: '/cv/print'
      path: '/cv/print'
      fullPath: '/cv/print'
      preLoaderRoute: typeof CvPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cv/edit': {
      id: '/cv/edit'
      path: '/cv/edit'
      fullPath: '/cv/edit'
      preLoaderRoute: typeof CvEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CvsRoute: CvsRoute,
  ProfilesRoute: ProfilesRoute,
  TemplatesRoute: TemplatesRoute,
  CvEditRoute: CvEditRoute,
  CvPrintRoute: CvPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
